/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as MattersRouteImport } from './routes/matters'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as StackRouteImport } from './routes/stack'
import { Route as TriadRouteImport } from './routes/triad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersRoute = MattersRouteImport.update({
  id: '/matters',
  path: '/matters',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const TriadRoute = TriadRouteImport.update({
  id: '/triad',
  path: '/triad',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draft': typeof DraftRoute
  '/intake': typeof IntakeRoute
  '/matters': typeof MattersRoute
  '/playbook': typeof PlaybookRoute
  '/research': typeof ResearchRoute
  '/stack': typeof StackRoute
  '/triad': typeof TriadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draft': typeof DraftRoute
  '/intake': typeof IntakeRoute
  '/matters': typeof MattersRoute
  '/playbook': typeof PlaybookRoute
  '/research': typeof ResearchRoute
  '/stack': typeof StackRoute
  '/triad': typeof TriadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/draft': typeof DraftRoute
  '/intake': typeof IntakeRoute
  '/matters': typeof MattersRoute
  '/playbook': typeof PlaybookRoute
  '/research': typeof ResearchRoute
  '/stack': typeof StackRoute
  '/triad': typeof TriadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/draft'
    | '/intake'
    | '/matters'
    | '/playbook'
    | '/research'
    | '/stack'
    | '/triad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/draft'
    | '/intake'
    | '/matters'
    | '/playbook'
    | '/research'
    | '/stack'
    | '/triad'
  id:
    | '__root__'
    | '/'
    | '/draft'
    | '/intake'
    | '/matters'
    | '/playbook'
    | '/research'
    | '/stack'
    | '/triad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DraftRoute: typeof DraftRoute
  IntakeRoute: typeof IntakeRoute
  MattersRoute: typeof MattersRoute
  PlaybookRoute: typeof PlaybookRoute
  ResearchRoute: typeof ResearchRoute
  StackRoute: typeof StackRoute
  TriadRoute: typeof TriadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters': {
      id: '/matters'
      path: '/matters'
      fullPath: '/matters'
      preLoaderRoute: typeof MattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triad': {
      id: '/triad'
      path: '/triad'
      fullPath: '/triad'
      preLoaderRoute: typeof TriadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DraftRoute: DraftRoute,
  IntakeRoute: IntakeRoute,
  MattersRoute: MattersRoute,
  PlaybookRoute: PlaybookRoute,
  ResearchRoute: ResearchRoute,
  StackRoute: StackRoute,
  TriadRoute: TriadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
